### ISSUE TITLE
Is vg-complete called?

### ISSUE THREAD

**Issue by ronky** [NamPNQ/bower-videogular-youtube#24]
Hi,

when youtube video is finished playing, is the method in vg-complete called?

```html
<videogular vg-theme="videoConfig.theme.url" class="videogular-container" vg-complete="onCompleteVideoPlay()" vg-player-ready="onPlayerReady($API)">
    <vg-media vg-src="videoConfig.sources" vg-youtube="rel=1;showinfo=1"></vg-media>
</videogular>
```

```javascript
$scope.onCompleteVideoPlay = function () {
                if (secondScreenCtrl.API) {
                    secondScreenCtrl.API.toggleFullScreen();
                    $scope.playingVideo = false;
                } else {
                    throw new Error('video player API not ready!');
                }
};
```

**Comment by DerekNien** [comment]
I think it won't call the method in vg-complete.
Since the author did not register YouTube API's ```onStateChange``` event (See [YouTube IFrame API](https://developers.google.com/youtube/iframe_api_reference#Events)) and trigger the **ended** event when the YouTube video ends. The **ended** event is listened by ```API.mediaElement[0]``` (See [vg-controller.js](https://github.com/2fdevs/videogular/blob/master/app/scripts/com/2fdevs/videogular/controllers/vg-controller.js#L296)). So the  ```onComplete``` API event handler of videogular (See [vg-controller.js](https://github.com/2fdevs/videogular/blob/master/app/scripts/com/2fdevs/videogular/controllers/vg-controller.js#L280)) won't be called and hence the method in vg-complete won't be called, either.

**Comment by ronky** [comment]
I've created a pull request https://github.com/NamPNQ/bower-videogular-youtube/pull/26

**Comment by ronky** [comment]
Thanks @DerekNien for pointing me in the right direction.

**Comment by DerekNien** [comment]
You're welcome. :)
And thank you for your pull request.
