### ISSUE TITLE
Conflict between angular-video-bg and videogular-youtube

### ISSUE THREAD

**Issue by PierrickGT** [NamPNQ/bower-videogular-youtube#51]
Hi everybody,

I've spent the last couple hours trying to figure out why videogular-youtube didn't work in my app and I've found out that it was because there is a strange conflict happening with [angular-video-bg](https://github.com/kanzelm3/angular-video-bg).

I guess it's because the plugins both use the same method to retrieve the Youtube videos and I would like to know if some people got the same problem and how they resolved it.

**Comment by NamPNQ** [comment]
@PierrickGT Can you provide your source code

**Comment by PierrickGT** [comment]
@NamPNQ here is a quick Codepen to show you the problem. http://codepen.io/PierrickGT/pen/RrxJVQ

If you uncomment 
```haml
%video-bg{"video-id" => "'aYf7JyUghIs'"} 
```
you'll see that the Youtube video doesn't load anymore.
Instead, Videogular loads the MP4 video.

**Comment by NamPNQ** [comment]
@PierrickGT The reason is angular-video-bg line 473 
![image](https://cloud.githubusercontent.com/assets/2740696/12550524/e9ff1b5a-c396-11e5-81e3-3560fdb52a75.png)
 had overload my function `$window.onYouTubeIframeAPIReady`, and I can not detect youtube api had loaded, I have a solution for you, add `$rootScope.youtubeApiReady = true;` to after `ytd.resolve();`

**Comment by PierrickGT** [comment]
Thank you!

For now, I've used a simple HTML5 video for the background video.
But I'm gonna keep your solution in mind if I want to use angular-video-bg again later.

Thank you again for your help and have a good week.

**Comment by NamPNQ** [comment]
@PierrickGT No problems
Here for you https://gist.github.com/NamPNQ/aa47aefd9f7c6bbfea23
